import { projects, artwork } from './projects.js';
import './journey.css';
import './grain.css';
import './contact.js';
// Initialize after the synchronous project and case-study markup is rendered.
import('./motion.js');
const list=document.querySelector('#project-list');
if(list) list.innerHTML=projects.map((p,i)=>`<article class="project"><div class="project-copy"><span class="eyebrow">0${i+1} / ${p.category}</span><h3>${p.name}</h3><p>${p.summary}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><a class="text-link" href="/case-study.html?project=${p.id}">Explore ${p.name} ↗</a></div><a href="/case-study.html?project=${p.id}" aria-label="Read the ${p.name} project story">${artwork(p)}</a></article>`).join('');
const time=document.querySelector('#local-time');
if(time){const update=()=>time.textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Lagos',hour:'2-digit',minute:'2-digit'}).format(new Date());update();setInterval(update,60000);}
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
document.querySelector('#copy-email')?.addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('templegideon001@gmail.com');status.textContent='Email copied.';}catch{status.textContent='Please select and copy the email address.';}});
const detail=document.querySelector('#case-content');
if(detail){const requestedId=new URLSearchParams(location.search).get('project');const id=requestedId==='jenom'?'jai':requestedId;const p=projects.find(p=>p.id===id);if(!p){document.title='Project not found - Temple Gideon';detail.innerHTML='<h1>Project not found.</h1><p>Choose a project from the selected work.</p><a class="text-link" href="/#work">Back to selected work ↗</a>';}else{document.title=`${p.name} - Temple Gideon`;document.querySelector('meta[name="description"]').content=p.summary;const next=projects[(projects.indexOf(p)+1)%projects.length];detail.innerHTML=`<a class="text-link" href="/#work">← Selected work</a><h1>${p.name}</h1><p class="case-deck">${p.summary}</p>${artwork(p)}<div class="case-layout"><aside><span class="eyebrow">${p.category}</span><p>${p.status}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>${p.link?`<a class="text-link" href="${p.link}" target="_blank" rel="noopener noreferrer">${p.linkLabel} ↗</a>`:'<p>Source code is private.</p>'}</aside><div class="case-body"><h2>The problem</h2><p>${p.problem}</p><h2>How the pieces connect</h2><p>${p.system}</p><h2>A decision that matters</h2><p>${p.decision}</p><h2>Inside the project</h2><ul>${p.details.map(d=>`<li>${d}</li>`).join('')}</ul>${p.results?`<h2>Model evaluation</h2><p>${p.results}</p>`:""}<h2>${p.scopeHeading || "Current scope"}</h2><p>${p.limitations}</p></div></div><div class="case-bottom"><a class="text-link" href="/#work">← All work</a><a class="text-link" href="/case-study.html?project=${next.id}">Next: ${next.name} →</a></div>`;}}
